GRANT ALL PRIVILEGES ON DATABASE {DB명} TO {사용자};
GRANT USAGE ON SCHEMA public TO {사용자};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO {사용자};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {사용자};